apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jeroenvisser-online-ingress
  namespace: jeroenvisser-online
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
spec:
  rules:
  - host: jeroenvisser.online
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: web
  namespace: jeroenvisser-online
  labels:
    run: web
spec:
  selector:
    run: web
  ports:
  - port: 80
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: web
  namespace: jeroenvisser-online
spec:
  replicas: 2
  progressDeadlineSeconds: 90
  template:
    metadata:
      labels:
        run: web
    spec:
      containers:
      - name: web
        image: jvisser/jeroenvisser.online-website:${GIT_HASH}
        imagePullPolicy: Always
        ports:
        - containerPort: 80