apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jeroenvisser-online-ingress
  namespace: ${KUBE_APP_NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
data:
  proxy-hide-headers: "Server"
  server-tokens: "False"
spec:
  tls:
  - hosts:
    - ${DOMAIN_NAME}
    secretName: letsencrypt-production
  rules:
  - host: ${DOMAIN_NAME}
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: web
  namespace: ${KUBE_APP_NAMESPACE}
  labels:
    run: web
spec:
  selector:
    run: web
  ports:
  - port: 80
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: web
  namespace: ${KUBE_APP_NAMESPACE}
spec:
  replicas: 2
  progressDeadlineSeconds: 90
  template:
    metadata:
      labels:
        run: web
    spec:
      containers:
      - name: web
        image: ${DOCKER_IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 80